---
name: Hourly
on:
    workflow_dispatch:
    schedule:
        - cron: "54 * * * *"
jobs:
    build:
        permissions:
          contents: write
          pull-requests: read
        runs-on: ubuntu-latest
        steps:
            - name: Check out Repo
              uses: actions/checkout@v4

            - name: Fetch latest Data file
              run: |-
                  curl "https://thechels.uk/feed" > _data/thechels.xml

            - name: Commit and push
              run: |-
                  git diff
                  git config user.name "GitHub Action"
                  git config user.email "action@github.com"
                  git diff --quiet || (git add -A && git commit -m "Updated `date +'%Y-%m-%d %H:%M:%S'`")
                  git push
